// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ChatGPT Clone",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import SideBar from "@/components/SideBar";
import "./globals.css";
import { SessionProvider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
export default async function RootLayout({
  children,
}: {
    children: React.ReactNode;
}){

  const session = await getServerSession(authOptions)
  return (
    <html>
      <head />
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login/>
          ): (
             <div className="flex">

             <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
             <SideBar />
             </div>
             {/* ClientProvider - Notification */}
             <div className="bg-[#343541] flex-1">{children}</div>
           </div>
          )}
       
        </SessionProvider>
      </body>
    </html>
  )
}

